### ISSUE TITLE
Propose new options for September 2019 f2f meeting

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttwg#30]
See discussion in minutes logged at #26

**Comment by nigelmegitt** [comment]
Proposal made in #27, quoting here for convenience:

> Proposal options:
>
>*    Meet in Fukuoka on the Thursday and Friday of TPAC, invite remote participation especially from Europe
>*    Meet in or near Amsterdam for one day, either 10th or 11th September, and also meet on the Thursday or Friday of TPAC.
>*    Look for a date to meet in July or August in Europe, with the option of inviting EBU Timed Text group jointly, and then meet again at TPAC.
>
>For reference, see the results of the [closed poll for f2f planning for September](https://www.w3.org/2002/09/wbs/34314/2019_September-F2F/results).

**Comment by cconcolato** [comment]
@nigelmegitt can you split option 2? I thought the idea was to meet before or after IBC, not both.

**Comment by nigelmegitt** [comment]
As discussed on today's call, please add any other options you'd like to see here.

**Comment by cconcolato** [comment]
I think we should also think about the agenda for this meeting. If we keep our current goal (publications by the end of the year), a meeting in September will probably not be useful for this goal. It may be useful for discussing the next ones. So maybe we should think about Option 3 a bit more and have a meeting in May/June to help us achieve our goal for 2019, and keep the meeting at TPAC for next goals.

**Comment by nigelmegitt** [comment]
> I thought the idea was to meet before or after IBC, not both.

@cconcolato It may have been _one_ idea, but based on the discussion, it did not seem completely out of the question, so it is still an option. There's good reason from the survey results and the discussion to think we would have attendance at both, though probably not all the same people.

**Comment by nigelmegitt** [comment]
@cconcolato I'd be amenable to thinking about adding June as a possibility to option 3 - face to face meetings are certainly helpful when we are in the thick of making specification changes. I think May could be too soon to arrange though.

**Comment by tairt** [comment]
I see three realistic options (assuming for now the original idea of having one f2f):

1. Meet before IBC in Amsterdam (e.g. 10-11 Sep)
1. Meet after IBC in Amsterdam (e.g. 17-18 Sep)
1. Meet at TPAC in Fukuoka (e.g. 17-18 Sep)

One way to check if option 1 and 2 can be considered is, to contact the members that have indicated that they could not join in Amsterdam and see if we can find a solution that satisfies their needs.

For the idea of @cconcolato to have two f2f meetings (one of them during TPAC) we may want to check availability and roadmap. I think that @cconcolato is right that we need to look at what we want would like to achieve and then find the appropriate means. This include the appropriate dates but of course also the right people so that we can resolve what is necessary at a certain point in time.

**Comment by simpson-matt** [comment]
I will definitely be at IBC, as will the majority of media / broadcast tech folk who travel as part of their roles. Getting the agreement to go to Japan could be feasible at another point in the year, but realistically I can't physically dash from Amsterdam to Fukuoka overnight, having spent 5 days on my feet on a trade show booth.

**Comment by palemieux** [comment]
Regarding Fukuoka
============

Given that:

- some folks are unlikely to travel to Fukuoka, and are likely to be in Europe at the same time
- some folks are likely to travel to Fukuoka regardless whether TTWG meets
- there are no known agenda items for Fukuoka at this point
- it is probably easier to reserve space a Fukuoka now and cancel later, than request a space later

I would assume that:

- it is unlikely that extensive discussions can be held in Fukuoka due to lack of quorum/expertise
- it is reasonable that focused sessions, esp. jointly with other groups, could be held at Fukuoka

I would therefore think it is not unreasonable to:

- book room space at Fukuoka, with the understanding that limited to no actual meetings will occur
- put on the calendar a 4-hour session with remote participation with times convenient for Europe

Regarding other meetings
=================

I recommend tentatively scheduling a F2F in Europe or in US, in line with the timeline of record such that the meeting will likely coincide with achieving consensus on transition to CR.

**Comment by nigelmegitt** [comment]
Since no new dates will now be proposed for a September F2F in addition to Fukuoka, I'm closing this.
